export const GET_PROJECTS = 'GET_PROJECTS';
export const SET_ACTIVE_PROJECTS = 'SET_ACTIVE_PROJECTS';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_YESTERDAY_WORKLOGS = 'SET_YESTERDAY_WORKLOGS';
